# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests3D
 
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      event_type:
        required: true
        type: string
      action_type:
        required: true
        type: string
jobs:
  build:
    environment: test3d
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: check_3d_modified
      uses: dorny/paths-filter@v2
      id: filter3d
      with:
        filters: |
          mesh3d:
            - 'warmth/warmth3d/**'
      
    - name: Run
      uses: tj-actions/docker-run@v2
      if: ${{ steps.filter3d.outputs.mesh3d }} == 'true'
      with:
        image: ghcr.io/equinor/warmth:latest
        name: dolfinx
        options: -v ${{ github.workspace }}:/home/warmth


    - name: Comment coverage
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' && steps.filter3d.outputs.mesh3d == 'true' }}
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
