# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests3D
 
on:
  workflow_call:
    inputs:
      event_type:
        required: true
        type: string
      action_type:
        required: true
        type: string
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run
      uses: tj-actions/docker-run@v2
      with:
        image: dolfinx/dolfinx:v0.7.0
        name: dolfinx
        options: -v ${{ github.workspace }}:/
        args: |
          pip install .
          pip install pytest==7.4.2 pytest-cov==4.1.0
          pytest --cov-report=term-missing --cov=warmth/3d tests/3d | tee pytest-coverage.txt


    - name: Comment coverage
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
